# Generated by Django 5.0.1 on 2024-01-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(max_length=255)),
                ('usb_ports', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('graphics_card', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('power_system', models.CharField(max_length=255)),
            ],
        ),
    ]
