# Generated by Django 5.0.3 on 2024-03-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_device_date_added_device_date_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='device',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
